//! #[tool] Proc Macro Example
//!
//! Demonstrates zero-boilerplate tool registration using the `#[tool]` attribute macro.
//! Compare with the `function_tool` example to see the ergonomic improvement.
//!
//! ```bash
//! GOOGLE_API_KEY=... cargo run --example tool_macro
//! ```

use adk_agent::LlmAgentBuilder;
use adk_core::AdkError;
use adk_model::gemini::GeminiModel;
use adk_tool::tool;
use schemars::JsonSchema;
use serde::Deserialize;
use serde_json::{Value, json};
use std::sync::Arc;

// --- Define tools with #[tool] macro ---
// Doc comments become the tool description.
// The args struct provides the JSON schema via schemars.

#[derive(Deserialize, JsonSchema)]
struct WeatherArgs {
    /// The city to get weather for
    city: String,
    /// Temperature unit (celsius or fahrenheit)
    unit: Option<String>,
}

/// Get the current weather for a city.
#[tool]
async fn get_weather(args: WeatherArgs) -> Result<Value, AdkError> {
    let unit = args.unit.unwrap_or_else(|| "celsius".to_string());
    let temp = match unit.as_str() {
        "fahrenheit" => 72,
        _ => 22,
    };
    Ok(json!({
        "city": args.city,
        "temperature": temp,
        "unit": unit,
        "condition": "sunny"
    }))
}

#[derive(Deserialize, JsonSchema)]
struct CalcArgs {
    /// The arithmetic operation: add, subtract, multiply, divide
    operation: String,
    /// First number
    a: f64,
    /// Second number
    b: f64,
}

/// Perform basic arithmetic calculations.
#[tool]
async fn calculator(args: CalcArgs) -> Result<Value, AdkError> {
    let result = match args.operation.as_str() {
        "add" => args.a + args.b,
        "subtract" => args.a - args.b,
        "multiply" => args.a * args.b,
        "divide" => {
            if args.b == 0.0 {
                return Err(AdkError::Tool("division by zero".to_string()));
            }
            args.a / args.b
        }
        op => return Err(AdkError::Tool(format!("unknown operation: {op}"))),
    };
    Ok(json!({ "result": result }))
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let api_key = std::env::var("GOOGLE_API_KEY")
        .or_else(|_| std::env::var("GEMINI_API_KEY"))
        .expect("GOOGLE_API_KEY or GEMINI_API_KEY must be set");

    let model = GeminiModel::new(&api_key, "gemini-2.5-flash")?;

    // Tools are zero-sized structs — just Arc::new() them
    let agent = LlmAgentBuilder::new("assistant")
        .description("Assistant with weather and calculator tools")
        .instruction(
            "You are a helpful assistant. Use the get_weather tool for weather questions \
             and the calculator tool for math. Be concise.",
        )
        .model(Arc::new(model))
        .tool(Arc::new(GetWeather)) // Generated by #[tool] macro
        .tool(Arc::new(Calculator)) // Generated by #[tool] macro
        .build()?;

    println!("Tools registered via #[tool] macro:");
    println!("  - GetWeather (from get_weather fn)");
    println!("  - Calculator (from calculator fn)");
    println!("\nTry: 'What is the weather in Tokyo?' or 'What is 99 * 42?'\n");

    adk_cli::console::run_console(
        Arc::new(agent),
        "tool_macro_app".to_string(),
        "user1".to_string(),
    )
    .await?;

    Ok(())
}
