//! MCP server that publishes a resource and a prompt, and emits resource-update
//! notifications.
//!
//! Exposes:
//! - a **resource** `config://app/review-policy` (the current PR review policy)
//! - a **prompt** `review_pr` (a policy-aware review instruction template)
//! - a **tool** `refresh_policy` that rotates the policy and sends
//!   `notifications/resources/updated` to every subscriber
//!
//! Spawned as a subprocess by the client and speaks MCP over stdio.

use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex};

use rmcp::{
    ErrorData as McpError, ServerHandler,
    handler::server::router::tool::ToolRouter,
    model::{
        GetPromptRequestParams, GetPromptResult, ListPromptsResult, ListResourcesResult,
        PaginatedRequestParams, Prompt, PromptArgument, PromptMessage, ReadResourceRequestParams,
        ReadResourceResult, Resource, ResourceContents, ResourceUpdatedNotificationParam, Role,
        ServerCapabilities, ServerInfo,
    },
    service::{RequestContext, RoleServer},
    tool, tool_handler, tool_router,
};
use serde_json::json;

const POLICY_URI: &str = "config://app/review-policy";

fn policy_text(revision: u64) -> String {
    format!(
        "Review policy v{revision}: require two approvals for any change that touches \
         authentication or billing; one approval otherwise. Block merges with failing CI."
    )
}

#[derive(Clone)]
struct ResourceServer {
    // Consumed by the handlers generated by `#[tool_handler]`.
    #[allow(dead_code)]
    tool_router: ToolRouter<Self>,
    policy: Arc<Mutex<String>>,
    revision: Arc<AtomicU64>,
}

impl ResourceServer {
    fn new() -> Self {
        Self {
            tool_router: Self::tool_router(),
            policy: Arc::new(Mutex::new(policy_text(1))),
            revision: Arc::new(AtomicU64::new(1)),
        }
    }
}

#[tool_router]
impl ResourceServer {
    #[tool(
        description = "Rotate the review policy to a new revision and notify subscribers that the \
                       policy resource changed"
    )]
    async fn refresh_policy(&self, context: RequestContext<RoleServer>) -> String {
        let revision = self.revision.fetch_add(1, Ordering::SeqCst) + 1;
        *self.policy.lock().expect("policy mutex poisoned") = policy_text(revision);

        // Tell every subscribed client that this resource's contents changed.
        let _ = context
            .peer
            .notify_resource_updated(ResourceUpdatedNotificationParam::new(POLICY_URI))
            .await;

        format!("Review policy rotated to revision {revision}")
    }
}

#[tool_handler]
impl ServerHandler for ResourceServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_prompts()
                .enable_resources()
                .enable_resources_subscribe()
                .build(),
        )
        .with_instructions(
            "Publishes the review policy as an MCP resource and a policy-aware review prompt. \
             Call refresh_policy to change the policy and notify subscribers.",
        )
    }

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, McpError> {
        Ok(ListResourcesResult::with_all_items(vec![
            Resource::new(POLICY_URI, "review-policy")
                .with_title("PR review policy")
                .with_description("The review rules the agent must apply")
                .with_mime_type("text/plain"),
        ]))
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResult, McpError> {
        if request.uri == POLICY_URI {
            let text = self.policy.lock().expect("policy mutex poisoned").clone();
            Ok(ReadResourceResult::new(vec![ResourceContents::text(text, POLICY_URI)]))
        } else {
            Err(McpError::resource_not_found(
                "unknown resource URI",
                Some(json!({ "uri": request.uri })),
            ))
        }
    }

    async fn list_prompts(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListPromptsResult, McpError> {
        Ok(ListPromptsResult::with_all_items(vec![Prompt::new(
            "review_pr",
            Some("Review a pull request against the current policy"),
            Some(vec![
                PromptArgument::new("pr_title")
                    .with_description("Title of the pull request to review")
                    .with_required(true),
            ]),
        )]))
    }

    async fn get_prompt(
        &self,
        request: GetPromptRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<GetPromptResult, McpError> {
        if request.name != "review_pr" {
            return Err(McpError::invalid_params("unknown prompt name", None));
        }
        let pr_title = request
            .arguments
            .as_ref()
            .and_then(|args| args.get("pr_title"))
            .and_then(|value| value.as_str())
            .unwrap_or("(untitled pull request)");
        let policy = self.policy.lock().expect("policy mutex poisoned").clone();
        let text = format!(
            "You are a meticulous code reviewer. Apply this policy exactly:\n\n{policy}\n\n\
             When asked, review the pull request titled: {pr_title}"
        );
        Ok(GetPromptResult::new(vec![PromptMessage::new_text(Role::User, text)])
            .with_description("Policy-aware pull-request review prompt"))
    }

    async fn subscribe(
        &self,
        _request: rmcp::model::SubscribeRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<(), McpError> {
        // Accept every subscription; refresh_policy will notify subscribers.
        Ok(())
    }
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let service =
        rmcp::ServiceExt::serve(ResourceServer::new(), rmcp::transport::io::stdio()).await?;
    service.waiting().await?;
    Ok(())
}
