//! Deterministic MCP server-manager example.
//!
//! The executable starts a tiny Rust MCP server as a child process, then uses
//! `McpServerManager` to manage it. No Node.js packages, API keys, or network
//! access are required.

use std::collections::HashMap;
use std::sync::Arc;
use std::time::Duration;

use adk_core::{ReadonlyContext, ToolContext, Toolset};
use adk_tool::mcp::manager::{McpServerConfig, McpServerManager, RestartPolicy};
use adk_tool::SimpleToolContext;
use rmcp::{
    ServerHandler,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{ServerCapabilities, ServerInfo},
    schemars, tool, tool_handler, tool_router,
};
use serde::Deserialize;
use serde_json::json;

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct EchoInput {
    /// Text the fixture server should return.
    message: String,
}

#[derive(Debug, Clone)]
struct FixtureServer {
    // Read by the handler generated by `#[tool_handler]`.
    #[allow(dead_code)]
    tool_router: ToolRouter<Self>,
}

impl FixtureServer {
    fn new() -> Self {
        Self { tool_router: Self::tool_router() }
    }
}

#[tool_router]
impl FixtureServer {
    #[tool(description = "Return the supplied message from the local MCP fixture server")]
    fn echo(&self, Parameters(input): Parameters<EchoInput>) -> String {
        format!("MCP server replied: {}", input.message)
    }
}

#[tool_handler]
impl ServerHandler for FixtureServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_instructions("Deterministic local server for the ADK-Rust MCP manager example")
    }
}

async fn run_fixture_server() -> anyhow::Result<()> {
    let service = rmcp::ServiceExt::serve(FixtureServer::new(), rmcp::transport::io::stdio()).await?;
    service.waiting().await?;
    Ok(())
}

fn fixture_config(disabled: bool) -> anyhow::Result<McpServerConfig> {
    Ok(McpServerConfig {
        command: std::env::current_exe()?.display().to_string(),
        args: vec!["--fixture-server".to_string()],
        env: HashMap::new(),
        disabled,
        auto_approve: Vec::new(),
        restart_policy: Some(RestartPolicy {
            initial_delay_ms: 100,
            max_delay_ms: 1_000,
            backoff_multiplier: 2.0,
            max_restart_attempts: 3,
        }),
    })
}

async fn run_demo() -> anyhow::Result<()> {
    println!("ADK-Rust dynamic MCP server manager\n");

    let initial = serde_json::to_string(&json!({
        "mcpServers": {
            "local-tools": fixture_config(false)?,
        }
    }))?;
    let manager = McpServerManager::from_json(&initial)?
        .with_name("product_mcp_servers")
        .with_health_check_interval(Duration::from_millis(250))
        .with_grace_period(Duration::from_secs(1));

    println!("1. Loaded local-tools from mcp.json-compatible configuration");
    manager.start_server("local-tools").await?;
    manager.start_monitoring();
    println!("   status: {:?}", manager.server_status("local-tools").await?);

    let readonly: Arc<dyn ReadonlyContext> = Arc::new(SimpleToolContext::new("mcp-manager-demo"));
    let tools = manager.tools(readonly).await?;
    println!("2. Discovered {} tool: {}", tools.len(), tools[0].name());

    let context: Arc<dyn ToolContext> = Arc::new(SimpleToolContext::new("mcp-manager-demo"));
    let response = tools[0]
        .execute(context, json!({ "message": "dynamic MCP is running" }))
        .await?;
    println!("3. Called the real child server");
    println!("   response: {response}");

    manager.add_server("standby-tools".into(), fixture_config(true)?).await?;
    println!("4. Added standby-tools at runtime: {:?}", manager.server_status("standby-tools").await?);
    manager.enable_server("standby-tools").await?;
    manager.start_server("standby-tools").await?;
    println!("   enabled and started: {:?}", manager.server_status("standby-tools").await?);

    let mut updated = fixture_config(false)?;
    updated.env.insert("MCP_DEPLOYMENT".into(), "blue".into());
    manager.update_server("standby-tools", updated).await?;
    println!("5. Reconfigured the running server and restarted it safely");

    let config_path = std::env::temp_dir().join("adk-rust-mcp-manager-example.json");
    manager.save_json_file(&config_path).await?;
    println!("6. Saved the live registry to {}", config_path.display());

    manager.disable_server("standby-tools").await?;
    manager.remove_server("standby-tools").await?;
    manager.shutdown().await?;
    let _ = tokio::fs::remove_file(config_path).await;
    println!("7. Disabled, removed, and shut down every child server");
    Ok(())
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    if std::env::args().any(|argument| argument == "--fixture-server") {
        run_fixture_server().await
    } else {
        run_demo().await
    }
}
