//! Validates: docs/official_docs/deployment/server.md (Full-Stack Example)
//!
//! Full-stack research paper generation example demonstrating complete client-server architecture.
//!
//! This example shows:
//! - Backend: ADK agent with custom research and PDF generation tools
//! - Frontend: Web application (see frontend.html in examples/research_paper/)
//! - Integration: REST API with SSE streaming, artifact management
//!
//! Business case: Deep research assistant that produces comprehensive research papers

use adk_rust::prelude::*;
use adk_rust::Launcher;
use adk_rust_guide::{init_env, is_interactive_mode, print_success, print_validating};
use serde_json::{json, Value};
use std::sync::Arc;

async fn conduct_research(_ctx: Arc<dyn ToolContext>, args: Value) -> Result<Value> {
    let topic = args["topic"]
        .as_str()
        .ok_or_else(|| AdkError::Tool("topic is required".to_string()))?;

    let depth = args["depth"].as_str().unwrap_or("comprehensive");

    // Simulate research process
    let findings = json!({
        "topic": topic,
        "depth": depth,
        "sources": [
            {
                "title": format!("Recent Advances in {}", topic),
                "summary": format!("This paper discusses the latest developments in {}.", topic),
                "relevance": "high"
            },
            {
                "title": format!("Historical Context of {}", topic),
                "summary": format!("An overview of how {} has evolved over time.", topic),
                "relevance": "medium"
            },
            {
                "title": format!("Future Directions in {}", topic),
                "summary": format!("Predictions and trends for the future of {}.", topic),
                "relevance": "high"
            }
        ],
        "key_findings": [
            format!("{} is a rapidly evolving field", topic),
            format!("Recent breakthroughs have transformed {}", topic),
            format!("Future research should focus on practical applications of {}", topic)
        ],
        "methodology": "Literature review and synthesis",
        "timestamp": chrono::Utc::now().to_rfc3339()
    });

    Ok(findings)
}

async fn generate_pdf(ctx: Arc<dyn ToolContext>, args: Value) -> Result<Value> {
    let title = args["title"]
        .as_str()
        .ok_or_else(|| AdkError::Tool("title is required".to_string()))?;

    let content = args["content"]
        .as_str()
        .ok_or_else(|| AdkError::Tool("content is required".to_string()))?;

    let author = args["author"].as_str().unwrap_or("Research Assistant");

    // Generate PDF content (simplified - in production use a PDF library)
    let pdf_content = format!(
        "Research Paper: {}\n\nAuthor: {}\n\nDate: {}\n\n{}\n\n---\nGenerated by ADK Research Assistant",
        title,
        author,
        chrono::Utc::now().format("%Y-%m-%d"),
        content
    );

    // Save as artifact
    if let Some(artifact_service) = ctx.artifacts() {
        let filename = format!("{}.pdf", title.replace(' ', "_").to_lowercase());
        let part = Part::Text {
            text: pdf_content.clone(),
        };

        artifact_service
            .save(&filename, &part)
            .await
            .map_err(|e| AdkError::Tool(format!("Failed to save PDF: {}", e)))?;

        Ok(json!({
            "status": "success",
            "filename": filename,
            "size_bytes": pdf_content.len(),
            "download_url": format!("/api/sessions/{}/{}/{}/artifacts/{}",
                ctx.app_name(),
                ctx.user_id(),
                ctx.session_id(),
                filename
            ),
            "message": "PDF generated successfully"
        }))
    } else {
        Err(AdkError::Tool(
            "Artifact service not available".to_string(),
        ))
    }
}

async fn format_citation(_ctx: Arc<dyn ToolContext>, args: Value) -> Result<Value> {
    let title = args["title"]
        .as_str()
        .ok_or_else(|| AdkError::Tool("title is required".to_string()))?;

    let authors = args["authors"].as_str().unwrap_or("Unknown");
    let year = args["year"].as_str().unwrap_or("n.d.");

    let citation = format!("{}. ({}). {}.", authors, year, title);

    Ok(json!({
        "citation": citation,
        "style": "APA"
    }))
}

#[tokio::main]
async fn main() -> std::result::Result<(), Box<dyn std::error::Error>> {
    let api_key = init_env();
    let model = Arc::new(GeminiModel::new(&api_key, "gemini-2.0-flash-exp")?);

    // Create research tool
    let research_tool = FunctionTool::new(
        "conduct_research",
        "Conduct deep research on a topic and return findings",
        conduct_research,
    );

    // Create PDF generation tool
    let generate_pdf_tool = FunctionTool::new(
        "generate_pdf",
        "Generate a PDF research paper from structured content",
        generate_pdf,
    );

    // Create citation tool
    let citation_tool = FunctionTool::new(
        "format_citation",
        "Format a citation in APA style",
        format_citation,
    );

    // Create the research agent
    let research_agent = LlmAgentBuilder::new("research_assistant")
        .description("An AI research assistant that conducts deep research and generates comprehensive research papers")
        .instruction(
            r#"You are an expert research assistant specializing in conducting thorough research and producing high-quality research papers.

Your workflow:
1. When given a research topic, use the conduct_research tool to gather information
2. Analyze the findings and synthesize them into a coherent narrative
3. Structure the content with:
   - Executive Summary
   - Introduction
   - Literature Review (based on research findings)
   - Key Findings and Analysis
   - Methodology
   - Conclusions and Future Directions
   - References (use format_citation tool)
4. Use the generate_pdf tool to create the final research paper

Be thorough, academic, and cite sources appropriately. Aim for comprehensive coverage of the topic.

When the user requests a research paper, follow this process:
1. Conduct research on the topic
2. Synthesize findings into structured sections
3. Generate citations for sources
4. Create the final PDF document
5. Provide the download link to the user

Always maintain a professional, academic tone."#
        )
        .model(model)
        .tool(Arc::new(research_tool))
        .tool(Arc::new(generate_pdf_tool))
        .tool(Arc::new(citation_tool))
        .build()?;

    let launcher = Launcher::new(Arc::new(research_agent)).app_name("research_paper_generator");

    if is_interactive_mode() {
        // Run in server mode for full-stack demo
        println!("🔬 Research Paper Generation System");
        println!("===================================\n");
        println!("This example demonstrates a full-stack application where:");
        println!("  • Frontend: Web UI for submitting research requests");
        println!("  • Backend: ADK agent that conducts research and generates PDFs");
        println!("  • Integration: REST API with SSE streaming\n");
        println!("Starting server...\n");

        launcher.run().await?;
    } else {
        // Validation mode
        print_validating("deployment/server.md (Full-Stack Example)");

        println!("✓ Research agent created successfully");
        println!("✓ Custom tools configured:");
        println!("  - conduct_research: Simulates deep research");
        println!("  - generate_pdf: Creates PDF documents");
        println!("  - format_citation: Formats APA citations");
        println!("✓ Launcher configured for server mode");
        println!("\nFull-stack features:");
        println!("  - REST API with SSE streaming");
        println!("  - Artifact storage for PDFs");
        println!("  - Session management");
        println!("  - Web UI integration");

        print_success("full_stack_research");
        println!("\nTip: Run with 'serve' for server mode:");
        println!("  cargo run --example full_stack_research -p adk-rust-guide -- serve");
        println!("\nFrontend: See examples/research_paper/frontend.html");
    }

    Ok(())
}
