//! OpenAI Research Paper Generation Example
//!
//! This example demonstrates a full-stack research paper generation system
//! using OpenAI. The agent can conduct research, format citations, and
//! generate structured research papers.
//!
//! Set OPENAI_API_KEY environment variable before running:
//! ```bash
//! export OPENAI_API_KEY=sk-...
//! cargo run --example openai_research_paper --features openai
//! ```

use adk_agent::LlmAgentBuilder;
use adk_cli::Launcher;
use adk_core::{AdkError, Part, ToolContext};
use adk_model::openai::{OpenAIClient, OpenAIConfig};
use adk_tool::FunctionTool;
use anyhow::Result;
use serde_json::{Value, json};
use std::sync::Arc;

async fn conduct_research(_ctx: Arc<dyn ToolContext>, args: Value) -> Result<Value, AdkError> {
    let topic =
        args["topic"].as_str().ok_or_else(|| AdkError::Tool("topic is required".to_string()))?;

    let depth = args["depth"].as_str().unwrap_or("comprehensive");

    // Simulate research process
    let findings = json!({
        "topic": topic,
        "depth": depth,
        "sources": [
            {
                "title": format!("Recent Advances in {}", topic),
                "summary": format!("This paper discusses the latest developments in {}.", topic),
                "relevance": "high"
            },
            {
                "title": format!("Historical Context of {}", topic),
                "summary": format!("An overview of how {} has evolved over time.", topic),
                "relevance": "medium"
            },
            {
                "title": format!("Future Directions in {}", topic),
                "summary": format!("Predictions and trends for the future of {}.", topic),
                "relevance": "high"
            }
        ],
        "key_findings": [
            format!("{} is a rapidly evolving field", topic),
            format!("Recent breakthroughs have transformed {}", topic),
            format!("Future research should focus on practical applications of {}", topic)
        ],
        "methodology": "Literature review and synthesis",
        "timestamp": chrono::Utc::now().to_rfc3339()
    });

    Ok(findings)
}

async fn generate_pdf(ctx: Arc<dyn ToolContext>, args: Value) -> Result<Value, AdkError> {
    let title =
        args["title"].as_str().ok_or_else(|| AdkError::Tool("title is required".to_string()))?;

    let content = args["content"]
        .as_str()
        .ok_or_else(|| AdkError::Tool("content is required".to_string()))?;

    let author = args["author"].as_str().unwrap_or("Research Assistant");

    // Generate PDF content (simplified - in production use a PDF library)
    let pdf_content = format!(
        "Research Paper: {}\n\nAuthor: {}\n\nDate: {}\n\n{}\n\n---\nGenerated by ADK Research Assistant (OpenAI)",
        title,
        author,
        chrono::Utc::now().format("%Y-%m-%d"),
        content
    );

    // Save as artifact
    if let Some(artifact_service) = ctx.artifacts() {
        let filename = format!("{}.pdf", title.replace(' ', "_").to_lowercase());
        let part = Part::Text { text: pdf_content.clone() };

        artifact_service
            .save(&filename, &part)
            .await
            .map_err(|e| AdkError::Tool(format!("Failed to save PDF: {}", e)))?;

        Ok(json!({
            "status": "success",
            "filename": filename,
            "size_bytes": pdf_content.len(),
            "download_url": format!("/api/sessions/{}/{}/{}/artifacts/{}",
                ctx.app_name(),
                ctx.user_id(),
                ctx.session_id(),
                filename
            ),
            "message": "PDF generated successfully"
        }))
    } else {
        Err(AdkError::Tool("Artifact service not available".to_string()))
    }
}

async fn format_citation(_ctx: Arc<dyn ToolContext>, args: Value) -> Result<Value, AdkError> {
    let title =
        args["title"].as_str().ok_or_else(|| AdkError::Tool("title is required".to_string()))?;

    let authors = args["authors"].as_str().unwrap_or("Unknown");
    let year = args["year"].as_str().unwrap_or("n.d.");

    let citation = format!("{}. ({}). {}.", authors, year, title);

    Ok(json!({
        "citation": citation,
        "style": "APA"
    }))
}

#[tokio::main]
async fn main() -> Result<()> {
    let api_key = std::env::var("OPENAI_API_KEY").expect("OPENAI_API_KEY must be set");

    let model = Arc::new(OpenAIClient::new(OpenAIConfig::new(api_key, "gpt-5-mini"))?);

    // Create research tool
    let research_tool = FunctionTool::new(
        "conduct_research",
        "Conduct deep research on a topic and return findings",
        conduct_research,
    );

    // Create PDF generation tool
    let generate_pdf_tool = FunctionTool::new(
        "generate_pdf",
        "Generate a PDF research paper from structured content",
        generate_pdf,
    );

    // Create citation tool
    let citation_tool =
        FunctionTool::new("format_citation", "Format a citation in APA style", format_citation);

    // Create the research agent
    let research_agent = LlmAgentBuilder::new("research_assistant")
        .description("An AI research assistant that conducts deep research and generates comprehensive research papers")
        .instruction(
            r#"You are an expert research assistant specializing in conducting thorough research and producing high-quality research papers.

Your workflow:
1. When given a research topic, use the conduct_research tool to gather information
2. Analyze the findings and synthesize them into a coherent narrative
3. Structure the content with:
   - Executive Summary
   - Introduction
   - Literature Review (based on research findings)
   - Key Findings and Analysis
   - Methodology
   - Conclusions and Future Directions
   - References (use format_citation tool)
4. Use the generate_pdf tool to create the final research paper

Be thorough, academic, and cite sources appropriately. Aim for comprehensive coverage of the topic.

When the user requests a research paper, follow this process:
1. Conduct research on the topic
2. Synthesize findings into structured sections
3. Generate citations for sources
4. Create the final PDF document
5. Provide the download link to the user

Always maintain a professional, academic tone."#
        )
        .model(model)
        .tool(Arc::new(research_tool))
        .tool(Arc::new(generate_pdf_tool))
        .tool(Arc::new(citation_tool))
        .build()?;

    println!("OpenAI Research Paper Generation System");
    println!("=======================================\n");
    println!("This example demonstrates a full-stack application where:");
    println!("  - Frontend: Web UI for submitting research requests");
    println!("  - Backend: OpenAI-powered agent that conducts research and generates PDFs");
    println!("  - Integration: REST API with SSE streaming\n");
    println!("Try asking: 'Write a research paper on machine learning in healthcare'\n");

    // Run with Launcher (supports both console and server modes)
    Launcher::new(Arc::new(research_agent))
        .app_name("openai_research_paper_generator")
        .run()
        .await?;

    Ok(())
}
